# Generated by Django 2.0 on 2019-06-05 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190521_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
